import type { Metadata } from "next";
import { Layout, Menu } from "antd";
import { Content, Footer, Header } from "antd/es/layout/layout";
import "./globals.css";
import AntdRegistry from "@ant-design/nextjs-registry/lib/AntdRegistry";
import React, { FC, ReactNode } from "react";
import Link from "next/link";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: ReactNode;
}

const items = [
  { key: 0, label: <Link href={"/"}>Home</Link> },
  { key: 1, label: <Link href={"/posts"}>Posts</Link> },
  { key: 2, label: <Link href={"/albums"}>Albums</Link> },
  { key: 3, label: <Link href={"/todo"}>Todo</Link> },
];

const RootLayout: FC<RootLayoutProps> = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en">
      <body>
        <AntdRegistry>
          <Layout>
            <Header>
              <Menu items={items} mode="horizontal" />
            </Header>
            <Content>{children}</Content>
            <Footer>Footer</Footer>
          </Layout>
        </AntdRegistry>
      </body>
    </html>
  );
};

export default RootLayout;
